### PR TITLE
add another multiple inheritance test for member functions

### PR DESCRIPTION
**Pull request by hroskes**
This test is for when a member is defined in the second base class but not directly in the first, when both inherit from the same grandparent class.  It still fails post #30.

I can take a stab at a solution if you like.

### CODE REVIEW

**Comment by biqqles** [comment]
Drat, I knew I shouldn't have released so soon! I think I see why this is happening. Not sure how to fix yet.

**Comment by biqqles** [comment]
Turns out inheritance is really complicated!

**Comment by biqqles** [comment]
The only way to exactly match Python's behaviour, presumably, is to use MRO, but I _really_ don't want to have to hackily create classes twice to get this.

**Comment by biqqles** [comment]
OK, it's fixable for user methods quite trivially. The trick is to keep the dict passed to `type` as bare-bones as possible so that Python does the heavy lifting. Magic methods will require a little more work, I think the obvious way to do this is keep two dictionaries, one recording the attributes in the chain so as not to mess with dict any more than is necessary. That is ugly, however.

**Comment by biqqles** [comment]
btw, got this test to pass a while ago but stuck at another failing test!

**Comment by biqqles** [comment]
Should be all fixed! The class dict is now not touched at all except to add generated methods.

**Comment by hroskes** [comment]
Thank you so much, this looks great and works for all my tests!

Is there any chance we can get a release on pypi?

**Comment by biqqles** [comment]
Yes, I can do that.

**Comment by hroskes** [comment]
Thank you!

**Pull request merged**
