### PR TITLE
fix post_init with multiple inheritance

### PR DESCRIPTION
**Pull request by hroskes**

### CODE REVIEW

**Comment by biqqles** [comment]
Thanks, I'll take a look at this.

**Comment by biqqles** [comment]
Sorry for ignoring this, I've been very busy and also I want to fix #35 before turning my attention to this.

**Comment by hroskes** [comment]
No, thank you for everything!

**Comment by biqqles** [comment]
I cherry-picked your excellent test, then realised that this scenario is fixed with the original strategy thanks to the improvements in #35! As always, let me know if you have any issues.

**Comment by hroskes** [comment]
Thank you so much!  I'll run my workflows and let you know how it goes.

**Comment by hroskes** [comment]
I'm still seeing some corner cases that fail :( I'm so sorry

**Pull request closed without merging**
